[[redirects]]
  from = "http://princeexecutivetransport.com/*"
  to = "https://www.princeexecutivetransport.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://princeexecutivetransport.com/*"
  to = "https://www.princeexecutivetransport.com/:splat"
  status = 301
  force = true
